In [6]:
import pickle
import pandas as pd

In [19]:
classifier=pickle.load(open("freshRottenClassifier.sav","rb"))

In [20]:
df=pd.read_csv("processedData.csv")

In [29]:
df

,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c3878,c3879,c3880,c3881,c3882,c3883,c3884,c3885,c3886,c3887
0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
3,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,0.992157,0.992157,0.968627,0.992157,0.992157,0.968627,0.996078,0.996078,0.972549,0.996078,...,0.933333,0.976471,0.945098,0.921569,0.964706,0.929412,0.905882,0.929412,0.901961,0.878431
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16501,0.980392,0.980392,0.980392,0.980392,0.980392,0.980392,0.980392,0.980392,0.980392,0.980392,...,0.949020,0.964706,0.980392,0.968627,0.976471,0.976471,0.976471,0.976471,0.976471,0.976471
16502,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
16503,0.984314,0.984314,0.984314,0.984314,0.984314,0.984314,0.984314,0.984314,0.984314,0.984314,...,0.603922,0.325490,0.709804,0.623529,0.560784,0.823529,0.776471,0.874510,0.968627,0.952941
16504,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16505,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [28]:
[ans]=classifier.predict(df.head(1))
ans

1

In [30]:
df.shape

(16506, 3888)